language: clojure
lein: lein2
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.lein
    - $HOME/.m2
env:
  - LIBSODIUM_VERSION=1.0.18
install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz
  - wget https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz.sig
  - gpg --import libsodium.pub
  - gpg --verify libsodium-${LIBSODIUM_VERSION}.tar.gz.sig libsodium-${LIBSODIUM_VERSION}.tar.gz
  - tar xfz libsodium-${LIBSODIUM_VERSION}.tar.gz
  - cd libsodium-${LIBSODIUM_VERSION} && ./configure && make && make check && sudo make install
script:
  - lein with-profile +test cljfmt check
  - lein with-profile +test kibit
  - lein with-profile +test eastwood || true
  - lein with-profile +test ancient || true
  - lein test

after_success:
  - lein with-profile +test cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
